---
language: node_js
node_js:
  - "6"

sudo: required
dist: trusty

addons:
  chrome: stable

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add bower

install:
  - yarn install --non-interactive
  - bower install
  - npm rebuild node-sass

script:
  - yarn test
