---
language: node_js
node_js: 8.5

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - node_modules
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add bower

install:
  - yarn install --non-interactive
  - bower install

script:
  - yarn test
