---
language: node_js
node_js: 8.5

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - node_modules
  yarn: true

install:
  - yarn install --non-interactive
  - bower install

script:
  - yarn test
